name: IP Speed Test

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点跑一次
  workflow_dispatch:      # 手动触发

jobs:
  test-speed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run speed test
      run: python speed_test.py

    - name: Commit and push results
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add speed_results.txt
        git diff --quiet && echo "No changes to commit" || git commit -m "Update speed test results"
        git push
      env:
        # 使用自动生成的 GitHub Token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
